# Generated by Django 4.0.4 on 2022-05-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0002_alter_currency_options_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Настройки пользователя', 'verbose_name_plural': 'Настройки пользователей'},
        ),
        migrations.AddField(
            model_name='profile',
            name='main_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sym_app.currency'),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
    ]
