# Generated by Django 4.0.4 on 2022-05-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sym_app', '0003_alter_profile_options_profile_main_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название счёта')),
                ('balance', models.FloatField(default=0)),
                ('is_archive', models.BooleanField(blank=True, verbose_name='Архивный счёт?')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sym_app.currency', verbose_name='ID валюты')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
