# Generated by Django 4.0.4 on 2022-05-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0012_alter_operation_to_wallet_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type_of', models.CharField(max_length=10)),
                ('category_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultWallets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['user', 'pk'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['pk'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ['user', 'pk'], 'verbose_name': 'Счёт', 'verbose_name_plural': 'Счета'},
        ),
    ]
