# Generated by Django 4.0.4 on 2022-05-21 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0017_alter_operation_amount2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-pk'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
    ]
