# Generated by Django 4.0.4 on 2022-05-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0018_alter_operation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='from_wallet_id',
            field=models.ForeignKey(db_column='from_wallet_id', on_delete=django.db.models.deletion.CASCADE, related_name='from_wallet', to='sym_app.wallet', verbose_name='Счёт списания'),
        ),
    ]
