# Generated by Django 4.0.4 on 2022-05-21 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0019_alter_operation_from_wallet_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='from_wallet_id',
            new_name='from_wallet',
        ),
    ]
