# Generated by Django 4.0.4 on 2022-05-21 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0023_rename_category_id_operation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.CASCADE, to='sym_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='to_wallet',
            field=models.ForeignKey(blank=True, db_column='to_wallet', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_wallet', to='sym_app.wallet', verbose_name='Счёт получения'),
        ),
    ]
