# Generated by Django 4.0.4 on 2022-05-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0024_alter_operation_category_alter_operation_to_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.ForeignKey(db_column='category', on_delete=django.db.models.deletion.PROTECT, to='sym_app.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='from_wallet',
            field=models.ForeignKey(db_column='from_wallet', on_delete=django.db.models.deletion.PROTECT, related_name='from_wallet', to='sym_app.wallet', verbose_name='Счёт списания'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='to_wallet',
            field=models.ForeignKey(blank=True, db_column='to_wallet', default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='to_wallet', to='sym_app.wallet', verbose_name='Счёт получения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='budget',
            field=models.BooleanField(blank=True, default=False, verbose_name='Режим "бюджет" (в разработке...)'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='main_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='sym_app.currency', verbose_name='Основная валюта'),
        ),
    ]
