# Generated by Django 4.0.4 on 2022-05-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0025_alter_operation_category_alter_operation_from_wallet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['pk'], 'verbose_name': 'Валюта', 'verbose_name_plural': 'Валюты'},
        ),
        migrations.AlterModelOptions(
            name='operation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Операция', 'verbose_name_plural': 'Операции'},
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_reverse',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обратный обмен'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_budget',
            field=models.BooleanField(blank=True, default=False, verbose_name='Бюджет вкл./выкл. (в разработке...)'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.FloatField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sym_app.currency', verbose_name='Валюта'),
        ),
    ]
