# Generated by Django 4.0.4 on 2022-05-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0026_alter_currency_options_alter_operation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='exchange_reverse',
        ),
        migrations.AddField(
            model_name='currency',
            name='exchange_rate_reverse',
            field=models.FloatField(default=1, verbose_name='Курс (сколько стоит валюта exchange_to в валюте name)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currency',
            name='exchange_rate',
            field=models.FloatField(verbose_name='Курс (сколько стоит валюта name в валюте exchange_to)'),
        ),
    ]
