# Generated by Django 4.0.4 on 2022-05-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sym_app', '0028_operation_exchange_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='exchange_rate',
            field=models.FloatField(blank=True, default=1, verbose_name='Курс'),
        ),
    ]
